<#
    LIMS Print Hub - run 24/7 as a Windows service (production)
    ===========================================================
    Registers the hub as a Scheduled Task that:
      * starts automatically at system boot (before/without any login),
      * runs headless as LocalSystem (no console window to close),
      * restarts automatically if it ever crashes,
      * has no run-time limit.

    Uses only built-in Windows (Task Scheduler) - nothing to download. The hub's
    startup banner runs in QUIET mode here (stdout is redirected), so the ADMIN
    TOKEN / ENROLL KEY are NOT written to the log; read them from
    <data>\admin_token.txt / enroll_key.txt (Administrators only) or the dashboard.

    Usage (run elevated - use install-hub-service.bat which self-elevates):
      powershell -ExecutionPolicy Bypass -File install-hub-service.ps1 -Action install
      powershell -ExecutionPolicy Bypass -File install-hub-service.ps1 -Action status
      powershell -ExecutionPolicy Bypass -File install-hub-service.ps1 -Action uninstall
#>
[CmdletBinding()]
param(
    [ValidateSet('install', 'uninstall', 'status', 'start', 'stop', 'restart')][string]$Action = 'install',
    [string]$TaskName = 'LIMS Print Hub',
    [int]$Port = 8000,
    [string]$BindHost = '0.0.0.0'
)
$ErrorActionPreference = 'Stop'

function Assert-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    if (-not (New-Object Security.Principal.WindowsPrincipal($id)).IsInRole(
            [Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw 'Run as Administrator (use install-hub-service.bat, which self-elevates).'
    }
}

$HubDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$Py     = Join-Path $HubDir '.venv\Scripts\python.exe'
$App    = Join-Path $HubDir 'app.py'
$LogDir = Join-Path $HubDir 'data'
$Log    = Join-Path $LogDir 'service.log'
# A tiny launcher .cmd so the task can set env + redirect the log in one line.
$Launcher = Join-Path $HubDir 'run-hub-service.cmd'

function Write-Launcher {
    $cmd = @"
@echo off
REM Auto-generated by install-hub-service.ps1 - launches the hub headless for the service.
set "HUB_HOST=$BindHost"
set "HUB_PORT=$Port"
set "HUB_QUIET=1"
cd /d "%~dp0"
"$Py" "$App" >> "$Log" 2>&1
"@
    [System.IO.File]::WriteAllText($Launcher, $cmd, (New-Object System.Text.ASCIIEncoding))
}

$Req    = Join-Path $HubDir 'requirements.txt'
$PyDir  = Join-Path $HubDir 'python'   # private CPython so the SYSTEM service can run it

function Refresh-Path {
    $m = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $u = [Environment]::GetEnvironmentVariable('Path', 'User')
    $env:Path = ($m, $u | Where-Object { $_ }) -join ';'
}

function Find-Uv {
    Refresh-Path
    $cands = @((Join-Path $env:USERPROFILE '.local\bin\uv.exe'),
               (Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Links\uv.exe'))
    $c = Get-Command uv -ErrorAction SilentlyContinue
    if ($c) { return $c.Source }
    foreach ($p in $cands) { if (Test-Path $p) { return $p } }
    Write-Host '    uv not found - installing (needs internet, one time)...' -ForegroundColor Gray
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        try { winget install --id astral-sh.uv -e --silent --accept-source-agreements --accept-package-agreements | Out-Null } catch {}
        Refresh-Path; $c = Get-Command uv -ErrorAction SilentlyContinue; if ($c) { return $c.Source }
        foreach ($p in $cands) { if (Test-Path $p) { return $p } }
    }
    try { powershell -ExecutionPolicy Bypass -Command "irm https://astral.sh/uv/install.ps1 | iex" | Out-Null } catch {}
    Refresh-Path; $c = Get-Command uv -ErrorAction SilentlyContinue; if ($c) { return $c.Source }
    foreach ($p in $cands) { if (Test-Path $p) { return $p } }
    throw 'uv could not be installed. Install it from https://docs.astral.sh/uv/ and re-run.'
}

function Test-VenvOk {
    # Healthy = the venv python exists, its BASE interpreter still exists, and it
    # can import all hub dependencies. The base matters: a venv is just a launcher
    # over pyvenv.cfg's 'home' interpreter, and if that was removed (e.g. the venv
    # was built on the client's ProgramData CPython and the client toolkit was
    # uninstalled) the launcher dies with "No Python at ...". Any failure here must
    # return $false (-> rebuild), never crash ($ErrorActionPreference is 'Stop' and
    # a native command writing stderr under redirection becomes terminating).
    if (-not (Test-Path $Py)) { return $false }
    try {
        $cfgFile = Join-Path $HubDir '.venv\pyvenv.cfg'
        if (Test-Path $cfgFile) {
            $m = Select-String -Path $cfgFile -Pattern '^\s*home\s*=\s*(.+)$' | Select-Object -First 1
            if ($m) {
                $baseDir = $m.Matches[0].Groups[1].Value.Trim()
                if ($baseDir -and -not (Test-Path (Join-Path $baseDir 'python.exe'))) { return $false }
            }
        }
        & $Py -c "import fastapi, uvicorn, httpx, multipart" 2>$null
        return ($LASTEXITCODE -eq 0)
    } catch { return $false }
}

function Resolve-BasePython($uv) {
    # Prefer an already-present SYSTEM-accessible CPython 3.12 so we avoid a download:
    #  1) the hub's OWN private one under <hub>\python - preferred, because the hub
    #     controls its lifetime. Building on the client's interpreter couples the
    #     hub to the client toolkit: uninstalling the client deletes the venv's base
    #     and every hub start dies with "No Python at ...".
    #  2) the client's interpreter under %ProgramData%\VirtualCloudPrinter\python
    #     (fallback only - useful offline when the hub machine also runs a client)
    #  3) install a private one via uv.
    $pd = Join-Path $env:ProgramData 'VirtualCloudPrinter\python'
    foreach ($root in @($PyDir, $pd)) {
        if (Test-Path $root) {
            $p = Get-ChildItem -Path $root -Directory -Filter 'cpython-3.12*' -ErrorAction SilentlyContinue |
                 ForEach-Object { Join-Path $_.FullName 'python.exe' } | Where-Object { Test-Path $_ } | Select-Object -First 1
            if ($p) { return $p }
        }
    }
    Write-Host '    Installing a private CPython 3.12 under the hub folder...' -ForegroundColor Gray
    $env:UV_PYTHON_INSTALL_DIR = $PyDir
    New-Item -ItemType Directory -Force -Path $PyDir | Out-Null
    & $uv python install --install-dir $PyDir 3.12 | Out-Null
    $p = Get-ChildItem -Path $PyDir -Directory -Filter 'cpython-3.12*' -ErrorAction SilentlyContinue |
         ForEach-Object { Join-Path $_.FullName 'python.exe' } | Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $p) { throw "Could not obtain CPython 3.12 (looked in $pd and $PyDir)." }
    return $p
}

function Ensure-Venv {
    # Self-contained: build/repair the venv here (no need to run run.bat first).
    if (Test-VenvOk) { Write-Host '    [ok] venv present and healthy.' -ForegroundColor Green; return }
    if (Test-Path $Py) { Write-Host '    venv exists but is broken/incomplete - rebuilding from scratch.' -ForegroundColor Yellow }
    else { Write-Host '    No venv yet - building it now (self-contained; run.bat not required).' -ForegroundColor Gray }
    if (-not (Test-Path $Req)) { throw "requirements.txt not found ($Req) - is this the hub folder?" }
    try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}
    $uv = Find-Uv
    $basePy = Resolve-BasePython $uv
    $venv = Join-Path $HubDir '.venv'
    # UV_VENV_CLEAR=1 so an existing .venv is REPLACED without an interactive prompt
    # (plain `uv venv` on an existing dir refuses and keeps the old, broken venv).
    $env:UV_VENV_CLEAR = '1'
    Write-Host "    Creating the virtual environment (base: $basePy)..." -ForegroundColor Gray
    & $uv venv --python $basePy --relocatable $venv
    if ($LASTEXITCODE -ne 0) { throw "uv venv failed (exit $LASTEXITCODE)." }
    Write-Host '    Installing hub dependencies (fastapi, uvicorn, httpx, python-multipart)...' -ForegroundColor Gray
    & $uv pip install -r $Req --python $venv
    if ($LASTEXITCODE -ne 0) { throw "uv pip install failed (exit $LASTEXITCODE)." }
    if (-not (Test-VenvOk)) {
        $err = (& $Py -c "import fastapi, uvicorn, httpx, multipart" 2>&1 | Out-String).Trim()
        throw "venv smoke test failed after build. Python said: $err"
    }
    Write-Host '    [ok] venv built and verified.' -ForegroundColor Green
}

function Stop-HubProcesses {
    # Stop the scheduled task AND kill any lingering hub python process, so a
    # stale (e.g. old-code) instance can't keep holding the port. Killing by the
    # listening port catches a leftover run.bat instance too; killing by the
    # app.py command line catches a starting/non-listening one. Best-effort.
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    }
    $killed = @()
    try {
        Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
            Select-Object -ExpandProperty OwningProcess -Unique | ForEach-Object {
                try { Stop-Process -Id $_ -Force -ErrorAction SilentlyContinue; $killed += $_ } catch {}
            }
    } catch {}
    try {
        Get-CimInstance Win32_Process -Filter "Name='python.exe'" -ErrorAction SilentlyContinue |
            Where-Object { $_.CommandLine -and $_.CommandLine -like "*$App*" } | ForEach-Object {
                try { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue; $killed += $_.ProcessId } catch {}
            }
    } catch {}
    $killed = $killed | Sort-Object -Unique
    if ($killed.Count) { Write-Host ("    stopped hub process(es): {0}" -f ($killed -join ', ')) -ForegroundColor Gray }
    Start-Sleep -Milliseconds 800
}

function Do-Stop {
    Assert-Admin
    Stop-HubProcesses
    Write-Host "[ok] Hub stopped (task stopped + any process on port $Port killed)." -ForegroundColor Green
}

function Do-Start {
    Assert-Admin
    if (-not (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue)) {
        throw "Service '$TaskName' is not installed - run install first."
    }
    Start-ScheduledTask -TaskName $TaskName
    Write-Host "[ok] Hub start requested." -ForegroundColor Green
    Start-Sleep -Seconds 4; Do-Status
}

function Do-Restart {
    Assert-Admin
    if (-not (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue)) {
        throw "Service '$TaskName' is not installed - run install first."
    }
    Write-Host "Restarting the hub..." -ForegroundColor Cyan
    Stop-HubProcesses
    Start-ScheduledTask -TaskName $TaskName
    Write-Host "[ok] Hub restarted (fresh process picks up the current app.py)." -ForegroundColor Green
    Start-Sleep -Seconds 4; Do-Status
}

function Do-Install {
    Assert-Admin
    if (-not (Test-Path $App)) { throw "app.py not found ($App)." }
    # Kill any previously-running hub (old code / stale instance) BEFORE we
    # re-register + start, otherwise it keeps the port and the fresh process
    # can't bind - leaving the OLD dashboard being served.
    Stop-HubProcesses
    New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
    Ensure-Venv
    Write-Launcher

    # Ensure SYSTEM (the service account) + Administrators have Full control of the
    # data dir (tokens, DB, service key). Additive - we do NOT strip inheritance, so
    # an admin who also runs run.bat interactively keeps access (stripping it caused
    # a non-elevated run.bat to fail creating data\held). To fully lock out standard
    # users on a shared box, run it from an admin-owned path like C:\LIMSHub.
    & icacls "$LogDir" /grant "SYSTEM:(OI)(CI)F" "*S-1-5-32-544:(OI)(CI)F" | Out-Null

    $action    = New-ScheduledTaskAction -Execute $Launcher
    $trigger   = New-ScheduledTaskTrigger -AtStartup
    $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
    $settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable -RestartInterval (New-TimeSpan -Minutes 1) -RestartCount 999 `
        -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    }
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Principal $principal -Settings $settings `
        -Description 'LIMS Print Hub - central receiver (auto-start, auto-restart).' | Out-Null
    Start-ScheduledTask -TaskName $TaskName
    Write-Host "[ok] Service '$TaskName' installed and started (auto-starts at boot, restarts on crash)." -ForegroundColor Green
    Write-Host "     Log: $Log   (QUIET mode - no secrets logged)" -ForegroundColor Gray
    Write-Host "     Tokens: $LogDir\admin_token.txt / enroll_key.txt (Administrators only)." -ForegroundColor Gray
    Start-Sleep -Seconds 4
    Do-Status
}

function Do-Uninstall {
    Assert-Admin
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Stop-HubProcesses
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "[ok] Service '$TaskName' removed." -ForegroundColor Green
    } else { Write-Host "Service '$TaskName' is not installed." -ForegroundColor Yellow }
}

function Do-Status {
    $t = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if (-not $t) { Write-Host "Service '$TaskName': NOT INSTALLED" -ForegroundColor Yellow; return }
    $info = Get-ScheduledTaskInfo -TaskName $TaskName
    Write-Host ("Service '{0}': {1}" -f $TaskName, $t.State)
    Write-Host ("  Last run : {0}  (result 0x{1:X})" -f $info.LastRunTime, $info.LastTaskResult)
    Write-Host ("  Next run : {0}" -f $info.NextRunTime)
    try {
        $r = Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:{0}/healthz" -f $Port) -TimeoutSec 5
        Write-Host ("  Health   : HTTP {0} ({1})" -f [int]$r.StatusCode, $r.Content) -ForegroundColor Green
    } catch { Write-Host "  Health   : not responding yet on port $Port" -ForegroundColor Yellow }
}

switch ($Action) {
    'install'   { Do-Install }
    'uninstall' { Do-Uninstall }
    'status'    { Do-Status }
    'start'     { Do-Start }
    'stop'      { Do-Stop }
    'restart'   { Do-Restart }
}
